cyclomatic_complexity:
  warning: 15
  error: 20

line_length: 200

type_body_length:
  warning: 150
  error: 250

file_length:
  warning: 200
  error: 400

function_body_length:
  warning: 150
  error: 250

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey

identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1


#included:
#  - App
#  - Modules/ContactHeader/Sources
#  - Modules/ContactList/Sources
#  - Modules/Core/Sources
#  - Modules/Network/Sources
#  - Modules/Root/Sources
#  - Modules/Settings/Sources
#  - Modules/SharedModels/Sources

disabled_rules:
  - nesting
